### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by tborychowski** [franhp/youtubedl-web#1]
Hi,

Not sure if this is still maintained, but I'm having a problem when I try to run it.

1. Launched it via docker - the UI shows up.
2. Added a youtube link - it gets added.
3. The state is "Pending" and stays that way...

There are no errors in logs or browser console...

**Comment by markconcept** [comment]
I am also inpacted by this issue. Please resolve

**Comment by franhp** [comment]
apologies for the delay, I'll have a look at it
you may want to try @michaeltoohig 's fork in the meantime

**Comment by franhp** [comment]
may have been a case of running a very old youtube-dl version (error detection doesn't really work in that case, will work on that soon), which would have been understandable as the image in the docker hub was a year old.

I've just found out about the github actions and so I'm going to build the docker image more often now to prevent this issue from happening again.

Could you please try again with the new image?

**Comment by tborychowski** [comment]
@franhp just tested, and it works now! Thanks a lot!
